---
- hosts: dev
  become: True
  tasks:
    - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start the container
      docker_container:
        name: spring-boot-docker
        image: "vccran/spring-boot-docker:0.0.1"
        state: started
        published_ports:
          - 0.0.0.0:8080:8080